const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let pc=null,dc=null,localStream=null,connected=false,muted=false,config=null,currentProvider='local',partialAssistant='';
let audioCtx=null,analyser=null,vadTimer=null,mediaRecorder=null,voiceChunks=[],recording=false,speechTicks=0,silenceTicks=0,voiceStartedAt=0,processingVoice=false,speakingLocal=false;
function addBubble(role,text,extra=''){if(!text)return;const d=document.createElement('div');d.className=`bubble ${role}`;d.textContent=text;if(extra)d.title=extra;$('#transcript').appendChild(d);$('#transcript').scrollTop=$('#transcript').scrollHeight}
function setState(text,mode=''){$('#stateText').textContent=text;$('#orb').className=`orb ${mode}`.trim()}
function setConnected(on,label='Live'){connected=on;$('#connectBtn').textContent=on?'Stop Virag':'Start Virag';$('#muteBtn').disabled=!on;$('#interruptBtn').disabled=!on;const p=$('#statusPill');p.className=`status ${on?'live':'offline'}`;p.innerHTML=`<span></span> ${on?label:'Offline'}`;if(!on)setState('Ready when you are.')}
function sendEvent(ev){if(dc?.readyState==='open')dc.send(JSON.stringify(ev))}
async function connect(){if(connected)return disconnect();config=await window.virag.getConfig();currentProvider=config.aiProvider||'local';if(currentProvider==='local')return startLocalVoice();if(!config.hasApiKey){showView('settings');$('#keyState').textContent='Add your OpenAI API key first.';return}setState('Connecting to OpenAI…');try{pc=new RTCPeerConnection();const audio=$('#remoteAudio');pc.ontrack=e=>{audio.srcObject=e.streams[0];setState('Virag is speaking…','speaking')};dc=pc.createDataChannel('oai-events');dc.onopen=()=>{setConnected(true,'Cloud Live');setState(config.wakeMode?`Wake mode: say “${config.wakePhrase}”`:'Listening…','listening')};dc.onmessage=handleRealtimeEvent;dc.onclose=()=>setConnected(false);localStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});localStream.getTracks().forEach(t=>pc.addTrack(t,localStream));const offer=await pc.createOffer();await pc.setLocalDescription(offer);const answerSdp=await window.virag.createRealtimeCall(offer.sdp);await pc.setRemoteDescription({type:'answer',sdp:answerSdp})}catch(e){console.error(e);addBubble('assistant',`Connection error: ${String(e.message||e)}`);disconnect()}}
async function startLocalVoice(){setState('Checking free local engine…');try{const st=await window.virag.localStatus();if(!st.ok){showView('settings');renderLocalState(st);addBubble('assistant','Free Local AI is not fully installed yet. Open Settings → Free Local AI → Install / Repair Free Engine.');return}localStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});audioCtx=new (window.AudioContext||window.webkitAudioContext)();analyser=audioCtx.createAnalyser();analyser.fftSize=1024;audioCtx.createMediaStreamSource(localStream).connect(analyser);startVAD();setConnected(true,'Local · Free');setState(config.wakeMode?`Local listening · say “${config.wakePhrase}”`:'Local listening…','listening')}catch(e){addBubble('assistant',`Local voice error: ${e.message||e}`);showView('settings')}}
function startVAD(){const buf=new Uint8Array(analyser.fftSize),threshold=Math.max(.008,Number(config.voiceThreshold)||.025);vadTimer=setInterval(()=>{if(!analyser||muted||processingVoice||speakingLocal)return;analyser.getByteTimeDomainData(buf);let sum=0;for(const v of buf){const x=(v-128)/128;sum+=x*x}const rms=Math.sqrt(sum/buf.length);if(!recording){if(rms>threshold)speechTicks++;else speechTicks=Math.max(0,speechTicks-1);if(speechTicks>=2)beginUtterance()}else{if(rms<threshold*.75)silenceTicks++;else silenceTicks=0;if(silenceTicks>=12||Date.now()-voiceStartedAt>18000)endUtterance()}},60)}
function beginUtterance(){if(recording||!localStream)return;voiceChunks=[];silenceTicks=0;speechTicks=0;voiceStartedAt=Date.now();try{const preferred=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'';mediaRecorder=new MediaRecorder(localStream,preferred?{mimeType:preferred}:undefined)}catch{mediaRecorder=new MediaRecorder(localStream)}mediaRecorder.ondataavailable=e=>{if(e.data?.size)voiceChunks.push(e.data)};mediaRecorder.onstop=processUtterance;mediaRecorder.start(200);recording=true;setState('Listening…','listening')}
function endUtterance(){if(!recording)return;recording=false;try{mediaRecorder?.stop()}catch{}}
async function processUtterance(){if(!voiceChunks.length||Date.now()-voiceStartedAt<300)return;processingVoice=true;setState('Transcribing locally…');try{const blob=new Blob(voiceChunks,{type:mediaRecorder?.mimeType||'audio/webm'}),bytes=new Uint8Array(await blob.arrayBuffer()),r=await window.virag.localTranscribe(bytes,blob.type);let text=String(r.text||'').trim();if(!text||text.length<2)return;if(config.wakeMode){const wake=String(config.wakePhrase||'hey virag').toLowerCase(),lower=text.toLowerCase(),idx=lower.indexOf(wake);if(idx<0)return;text=text.slice(idx+wake.length).replace(/^[\s,.:;!?-]+/,'').trim();if(!text){speakingLocal=true;await window.virag.localSpeak('Yes?');speakingLocal=false;return}}addBubble('user',text);await askLocal(text,true)}catch(e){addBubble('assistant',`Local speech error: ${e.message||e}`)}finally{processingVoice=false;if(connected)setState(config.wakeMode?`Local listening · say “${config.wakePhrase}”`:'Local listening…','listening')}}
async function askLocal(text,speakReply=false){setState('Thinking locally…');try{const r=await window.virag.localChat(text),reply=String(r.text||'Done.');addBubble('assistant',reply,`Local model: ${r.model||''}`);if(speakReply&&connected&&!muted){speakingLocal=true;setState('Virag is speaking…','speaking');await window.virag.localSpeak(reply);speakingLocal=false}return reply}catch(e){const msg=String(e.message||e);addBubble('assistant',`Local AI error: ${msg}`);if(/not installed|not running|engine/i.test(msg))showView('settings')}}
function disconnect(){if(currentProvider==='local'){clearInterval(vadTimer);vadTimer=null;if(recording)endUtterance();try{audioCtx?.close()}catch{}audioCtx=null;analyser=null;window.virag.stopLocal().catch(()=>{})}try{dc?.close()}catch{}try{pc?.close()}catch{}localStream?.getTracks().forEach(t=>t.stop());pc=null;dc=null;localStream=null;setConnected(false)}
async function handleRealtimeEvent(ev){let data;try{data=JSON.parse(ev.data)}catch{return}if(data.type==='input_audio_buffer.speech_started')setState('Listening…','listening');if(data.type==='input_audio_buffer.speech_stopped')setState('Thinking…');if(data.type==='conversation.item.input_audio_transcription.completed')addBubble('user',data.transcript||'');if(data.type==='response.output_audio_transcript.delta')partialAssistant+=data.delta||'';if(data.type==='response.output_audio_transcript.done'){addBubble('assistant',data.transcript||partialAssistant);partialAssistant='';setState('Listening…','listening')}if(data.type==='response.output_text.done'){addBubble('assistant',data.text||'');setState('Listening…','listening')}if(data.type==='response.function_call_arguments.done'){addBubble('tool',`Running: ${data.name}`);let args={};try{args=JSON.parse(data.arguments||'{}')}catch{}const r=await window.virag.executeTool(data.name,args),output=r.ok?JSON.stringify(r.result):JSON.stringify({error:r.error});sendEvent({type:'conversation.item.create',item:{type:'function_call_output',call_id:data.call_id,output}});sendEvent({type:'response.create'})}if(data.type==='error')addBubble('assistant',`Realtime error: ${data.error?.message||'Unknown error'}`)}
async function sendText(){const input=$('#textInput'),text=input.value.trim();if(!text)return;input.value='';addBubble('user',text);config=await window.virag.getConfig();currentProvider=config.aiProvider||'local';if(currentProvider==='local'){await askLocal(text,connected);return}if(!connected){addBubble('assistant','Start Virag first for OpenAI realtime mode.');return}sendEvent({type:'conversation.item.create',item:{type:'message',role:'user',content:[{type:'input_text',text}]}});sendEvent({type:'response.create'});setState('Thinking…')}
function interrupt(){if(currentProvider==='local'){window.virag.stopLocal();speakingLocal=false;processingVoice=false;setState('Local listening…','listening')}else{sendEvent({type:'response.cancel'});sendEvent({type:'output_audio_buffer.clear'});setState('Listening…','listening')}}
function toggleMute(){muted=!muted;localStream?.getAudioTracks().forEach(t=>t.enabled=!muted);$('#muteBtn').textContent=muted?'◌':'⌁';setState(muted?'Microphone muted':currentProvider==='local'?'Local listening…':'Listening…',muted?'':'listening')}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));if(id==='settings')loadSettings();if(id==='memory')loadMemory()}
$$('.nav').forEach(n=>n.onclick=()=>showView(n.dataset.view));$('#connectBtn').onclick=connect;$('#sendBtn').onclick=sendText;$('#interruptBtn').onclick=interrupt;$('#muteBtn').onclick=toggleMute;$('#textInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendText()}});window.virag.onShortcutToggle(()=>{showView('assistant');if(!connected)connect()});window.virag.onLocalTool(d=>addBubble('tool',`Running locally: ${d.name}`));
function toggleProviderCards(){const local=$('#aiProvider').value==='local';$('#localCard').style.display=local?'block':'none';$('#openaiCard').style.display=local?'none':'block';$('#cloudBrainCard').style.display=local?'none':'block'}
$('#aiProvider').onchange=toggleProviderCards;
async function renderLocalState(st=null){try{st=st||await window.virag.localStatus();const parts=[];parts.push(st.server?'Ollama ✓':'Ollama missing');parts.push(st.modelInstalled?`${st.model} ✓`:`${st.model} missing`);parts.push(st.whisper&&st.ffmpeg&&st.whisperModel?'Voice ✓':'Voice engine missing');$('#localState').textContent=parts.join(' · ');$('#localState').className=st.ok?'oktext':'warntext'}catch(e){$('#localState').textContent=`Local engine check failed: ${e.message||e}`}}
async function loadSettings(){config=await window.virag.getConfig();$('#aiProvider').value=config.aiProvider||'local';toggleProviderCards();$('#keyState').textContent=config.hasApiKey?'API key saved securely.':'No API key saved (not needed in Free Local mode).';for(const id of ['realtimeModel','reasoningModel','voice','wakePhrase','localModel','localVisionModel','whisperModelPath','localVoice'])if($('#'+id))$('#'+id).value=config[id]??'';if($('#voiceThreshold'))$('#voiceThreshold').value=config.voiceThreshold??.025;for(const id of ['wakeMode','allowShellTools','allowUiAutomation','browserHeadless','launchAtLogin','autoUpdateEnabled','autoInstallUpdates'])$('#'+id).checked=Boolean(config[id]);renderLocalState();refreshUpdateState()}
$('#setupLocal').onclick=async()=>{const r=await window.virag.setupLocal();$('#localState').textContent=r.ok?'Windows Free AI setup opened. Let it finish, then press Re-check.':`Could not open installer: ${r.error}`};$('#checkLocal').onclick=()=>renderLocalState();
$('#saveKey').onclick=async()=>{const v=$('#apiKey').value.trim();if(!v){$('#keyState').textContent='Paste your OpenAI Platform secret key first.';return}const b=$('#saveKey');b.disabled=true;b.textContent='Testing…';$('#keyState').textContent='Checking key with OpenAI…';try{const result=await window.virag.saveApiKey(v);config=result;if(result.keySaved){$('#apiKey').value='';$('#keyState').textContent='API key verified and saved securely ✓'}else $('#keyState').textContent=`Not saved: ${result.keyError||'OpenAI rejected this key.'}`}catch(e){$('#keyState').textContent=`Could not save key: ${e.message||e}`}finally{b.disabled=false;b.textContent='Save & test'}};
$('#clearKey').onclick=async()=>{config=await window.virag.clearApiKey();$('#apiKey').value='';$('#keyState').textContent='Saved API key cleared.'};
$('#saveSettings').onclick=async()=>{config=await window.virag.saveConfig({aiProvider:$('#aiProvider').value,localModel:$('#localModel').value,localVisionModel:$('#localVisionModel').value,whisperModelPath:$('#whisperModelPath').value.trim(),localVoice:$('#localVoice').value.trim(),voiceThreshold:Number($('#voiceThreshold').value)||.025,realtimeModel:$('#realtimeModel').value.trim(),reasoningModel:$('#reasoningModel').value.trim(),voice:$('#voice').value,wakeMode:$('#wakeMode').checked,wakePhrase:$('#wakePhrase').value.trim().toLowerCase(),allowShellTools:$('#allowShellTools').checked,allowUiAutomation:$('#allowUiAutomation').checked,browserHeadless:$('#browserHeadless').checked,launchAtLogin:$('#launchAtLogin').checked,autoUpdateEnabled:$('#autoUpdateEnabled').checked,autoInstallUpdates:$('#autoInstallUpdates').checked});$('#saveSettings').textContent='Saved ✓';setTimeout(()=>$('#saveSettings').textContent='Save settings',1000);renderLocalState()};
async function loadMemory(){const items=await window.virag.getMemories(50),box=$('#memoryList');box.innerHTML='';if(!items.length){box.innerHTML='<div class="card"><small>No long-term memories yet. Tell Virag “remember that…”</small></div>';return}items.forEach(m=>{const d=document.createElement('div');d.className='memory-item';d.innerHTML='<div><p></p><small></small></div><button>Forget</button>';d.querySelector('p').textContent=m.text;d.querySelector('small').textContent=`${new Date(m.createdAt).toLocaleString()} · ${(m.tags||[]).join(', ')}`;d.querySelector('button').onclick=async()=>{await window.virag.forgetMemory(m.id);loadMemory()};box.appendChild(d)})}
$('#clearMemory').onclick=async()=>{if(confirm('Clear all Virag memories?')){await window.virag.clearMemory();loadMemory()}};
function renderUpdateState(st){const el=$('#updateState');if(!el||!st)return;const v=st.currentVersion?`v${st.currentVersion}`:'',latest=st.latestVersion?` → v${st.latestVersion}`:'';const map={idle:`Virag ${v}`,checking:'Checking for updates…','up-to-date':`Virag ${v} is up to date.`,available:`Update available ${latest}`,'downloading':`Downloading update… ${st.progress||0}%`,installing:'Installing update…',restarting:'Update installed. Restarting Virag…',error:`Update error: ${st.error||'Unknown error'}`};el.textContent=map[st.status]||`Virag ${v}${latest}`}
async function refreshUpdateState(){try{renderUpdateState(await window.virag.getUpdateState())}catch{}}if($('#checkUpdate'))$('#checkUpdate').onclick=async()=>renderUpdateState(await window.virag.checkForUpdates());window.virag.onUpdateStatus(st=>renderUpdateState(st));loadSettings();
